apiVersion: v1
kind: ServiceAccount
metadata:
  name: holidays-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: holidays-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: holidays-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: holidays-sa
    namespace: default
roleRef:
  kind: Role
  name: holidays-role
  apiGroup: rbac.authorization.k8s.io
