apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: holiday-db
spec:
  serviceName: "holiday-db"
  replicas: 1
  selector:
    matchLabels:
      app: holiday-db
  template:
    metadata:
      labels:
        app: holiday-db
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MONGO_URL
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
