apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-holiday-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: holiday-db-pv-2   # make sure this matches the PV name
  storageClassName: standard
