apiVersion: v1
kind: PersistentVolume
metadata:
  name: holiday-db-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/mongo-holiday
    type: DirectoryOrCreate
